In [224]:
import pandas as pd
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
v=pd.Series([10,20,30,40,50,'abc'])
v

0     10
1     20
2     30
3     40
4     50
5    abc
dtype: object

In [ ]:
s=pd.Series([10,20,30,40,50])
s.dtype

dtype('int64')

In [ ]:
s.values

array([10, 20, 30, 40, 50])

In [ ]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
s.name="calories"
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

In [ ]:
s[0]

np.int64(10)

In [ ]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [ ]:
s.iloc[-1]

np.int64(50)

In [ ]:
s.iloc[-2]

np.int64(40)

In [ ]:
s.iloc[3]

np.int64(40)

In [ ]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [ ]:
newindexnames=["apple","banana","grapes","orange","strawberry"]
s.index=newindexnames
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
s['grapes']

np.int64(30)

In [ ]:
s.iloc[2]

np.int64(30)

In [ ]:
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [ ]:
s.index

Index(['apple', 'banana', 'grapes', 'orange', 'strawberry'], dtype='object')

In [ ]:
# can not access by non integers keys
s
s.iloc[2:5]

grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
s.name

'calories'

In [ ]:
index=[1,2,3,4,5]
s.index=index
s

1    10
2    20
3    30
4    40
5    50
Name: calories, dtype: int64

In [ ]:
s.loc[1:4] # here we accesss through  the idex names not accoding to position

1    10
2    20
3    30
4    40
Name: calories, dtype: int64

In [ ]:
fruit_protein={
    "avocado":2.0,
    "guava":2.6,
    "blackberry":2.0,
    "oranges":0.9,
    "banana":1.1,
    "apples":0.3,
    "kiwi":1.1,
    "promegranate":1.7,
    "mango":0.8,
    "cherries":1.0
    }
s2=pd.Series(fruit_protein)
s2

avocado         2.0
guava           2.6
blackberry      2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
promegranate    1.7
mango           0.8
cherries        1.0
dtype: float64

In [ ]:
s2=pd.Series(fruit_protein,name="protein") # renaming
s2

avocado         2.0
guava           2.6
blackberry      2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
promegranate    1.7
mango           0.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
s2>1 # comaprison operator

avocado          True
guava            True
blackberry       True
oranges         False
banana           True
apples          False
kiwi             True
promegranate     True
mango           False
cherries        False
Name: protein, dtype: bool

In [ ]:
s2[s2>1]

avocado         2.0
guava           2.6
blackberry      2.0
banana          1.1
kiwi            1.1
promegranate    1.7
Name: protein, dtype: float64

In [ ]:
[(s2>0.5)&(s2<2)] # and operator

[avocado         False
 guava           False
 blackberry      False
 oranges          True
 banana           True
 apples          False
 kiwi             True
 promegranate     True
 mango            True
 cherries         True
 Name: protein, dtype: bool]

In [ ]:
s2[(s2>0.5)&(s2<2)]

oranges         0.9
banana          1.1
kiwi            1.1
promegranate    1.7
mango           0.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
s2[(s2>0.5)&(s2<=2)]

avocado         2.0
blackberry      2.0
oranges         0.9
banana          1.1
kiwi            1.1
promegranate    1.7
mango           0.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
s2[(s2>0.5)|(s2<=2)]  # or operator

avocado         2.0
guava           2.6
blackberry      2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
promegranate    1.7
mango           0.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
s2[~(s2>1)]    # not operator

oranges     0.9
apples      0.3
mango       0.8
cherries    1.0
Name: protein, dtype: float64

In [ ]:
# modifying series
s2["mango"]=2.8
s2

avocado         2.0
guava           2.6
blackberry      2.0
oranges         0.9
banana          1.1
apples          0.3
kiwi            1.1
promegranate    1.7
mango           2.8
cherries        1.0
Name: protein, dtype: float64

In [ ]:
s3=pd.Series([10,None,30,None,50])
s3

0    10.0
1     NaN
2    30.0
3     NaN
4    50.0
dtype: float64

In [ ]:
print(s.notnull()) #  it is true when the value is not a null value

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [ ]:
print(s.isnull()) # it is true when the value is null

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [ ]:
print(s.sum()) # it gives sum of all values

90.0

In [ ]:
print(s.notnull().sum()) # it gives non null values count

3

In [ ]:
print(s.isnull().sum()) # it gives null values count

2

In [ ]:
s4=pd.Series([10,None,30,'a',None,50])
s4

0      10
1    None
2      30
3       a
4    None
5      50
dtype: object

In [ ]:
print(s4.notnull())

0     True
1    False
2     True
3     True
4    False
5     True
dtype: bool

In [ ]:
print(s4.isnull())

0    False
1     True
2    False
3    False
4     True
5    False
dtype: bool

In [ ]:
print(s4.sum())

90.0

In [ ]:
print(s4.notnull().sum())

4

In [ ]:
import pandas as pd
data={
    "Name":["balasri","leela","srija","mouni","sravani","balasri"],
    "Age":[25,30,35,None,29,25],
    "Department":["HR","IT","Finance","IT","HR","HR"],
    "Salary":[50000,60000,70000,62000,None,50000]
    }
data

{'Name': ['balasri', 'leela', 'srija', 'mouni', 'sravani', 'balasri'],
 'Age': [25, 30, 35, None, 29, 25],
 'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'HR'],
 'Salary': [50000, 60000, 70000, 62000, None, 50000]}

In [ ]:
df=pd.DataFrame(data)
df

      Name   Age Department   Salary
0  balasri  25.0         HR  50000.0
1    leela  30.0         IT  60000.0
2    srija  35.0    Finance  70000.0
3    mouni   NaN         IT  62000.0
4  sravani  29.0         HR      NaN
5  balasri  25.0         HR  50000.0

In [ ]:
df.head(2)

      Name   Age Department   Salary
0  balasri  25.0         HR  50000.0
1    leela  30.0         IT  60000.0

In [ ]:
df.tail()

      Name   Age Department   Salary
1    leela  30.0         IT  60000.0
2    srija  35.0    Finance  70000.0
3    mouni   NaN         IT  62000.0
4  sravani  29.0         HR      NaN
5  balasri  25.0         HR  50000.0

In [ ]:
df.tail(3)

      Name   Age Department   Salary
3    mouni   NaN         IT  62000.0
4  sravani  29.0         HR      NaN
5  balasri  25.0         HR  50000.0

In [ ]:
df

      Name   Age Department   Salary
0  balasri  25.0         HR  50000.0
1    leela  30.0         IT  60000.0
2    srija  35.0    Finance  70000.0
3    mouni   NaN         IT  62000.0
4  sravani  29.0         HR      NaN
5  balasri  25.0         HR  50000.0

In [ ]:
df.iloc[1:3]

    Name   Age Department   Salary
1  leela  30.0         IT  60000.0
2  srija  35.0    Finance  70000.0

In [ ]:
df.loc[1:3]

    Name   Age Department   Salary
1  leela  30.0         IT  60000.0
2  srija  35.0    Finance  70000.0
3  mouni   NaN         IT  62000.0

In [ ]:
df.loc[1:3,["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance
3   NaN         IT

In [ ]:
df.iloc[1:3,:2]

    Name   Age
1  leela  30.0
2  srija  35.0

In [ ]:
df["Age"]

0    25.0
1    30.0
2    35.0
3     NaN
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df[["Age","Salary"]]

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  35.0  70000.0
3   NaN  62000.0
4  29.0      NaN
5  25.0  50000.0

In [ ]:
# drop
df.drop("Age",axis=1) # age column is removed

      Name Department   Salary
0  balasri         HR  50000.0
1    leela         IT  60000.0
2    srija    Finance  70000.0
3    mouni         IT  62000.0
4  sravani         HR      NaN
5  balasri         HR  50000.0

In [ ]:
df.shape

(6, 4)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
# brodcasting
df["Salary"]=df["Salary"]+5000
df["Salary"]

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4        NaN
5    55000.0
Name: Salary, dtype: float64

In [ ]:
# renaming the column
df.rename(columns={"Department":"Dept"} ,inplace=True )
df

      Name   Age     Dept   Salary
0  balasri  25.0       HR  55000.0
1    leela  30.0       IT  65000.0
2    srija  35.0  Finance  75000.0
3    mouni   NaN       IT  67000.0
4  sravani  29.0       HR      NaN
5  balasri  25.0       HR  55000.0

In [ ]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  63400.000000
std     4.147288   8532.291603
min    25.000000  55000.000000
25%    25.000000  55000.000000
50%    29.000000  65000.000000
75%    30.000000  67000.000000
max    35.000000  75000.000000

In [ ]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [ ]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [ ]:
df["promoted salary"]=df["Salary"]*10
df

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
3    mouni   NaN       IT  67000.0         670000.0
4  sravani  29.0       HR      NaN              NaN
5  balasri  25.0       HR  55000.0         550000.0

In [ ]:
# data cleaning
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
promoted salary    1
dtype: int64

In [ ]:
df.dropna() # it removes the null value row

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
5  balasri  25.0       HR  55000.0         550000.0

In [ ]:
df.dropna(how="any") # defalul is any

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
5  balasri  25.0       HR  55000.0         550000.0

In [ ]:
df.dropna(how="all") # if all the values in my row are null then we remove thet row

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
3    mouni   NaN       IT  67000.0         670000.0
4  sravani  29.0       HR      NaN              NaN
5  balasri  25.0       HR  55000.0         550000.0

In [ ]:
df.fillna(0)  # we get the output as 0.0[a value isthe aa value NaN  place lo replace avuthundhi] in the place of NaN

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
3    mouni   0.0       IT  67000.0         670000.0
4  sravani  29.0       HR      0.0              0.0
5  balasri  25.0       HR  55000.0         550000.0

In [ ]:
df.fillna(2)

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
3    mouni   2.0       IT  67000.0         670000.0
4  sravani  29.0       HR      2.0              2.0
5  balasri  25.0       HR  55000.0         550000.0

In [ ]:
df["Age"].fillna(df["Age"].mean()) # the null value is replaced with the average of age values (25+30+35+29+25)/5=28.8

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Salary"].fillna(df["Salary"].median())

0    55000.0
1    65000.0
2    75000.0
3    67000.0
4    65000.0
5    55000.0
Name: Salary, dtype: float64

In [ ]:
df["Age"].fillna(method="ffill")  #forward fill# null value is replaced by the before value [means null value gets before value]

/tmp/ipykernel_1047/2601818694.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="ffill")  #forward fill# null value is replaced by the before value [means null value gets before value]

0    25.0
1    30.0
2    35.0
3    35.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Age"].fillna(method="bfill") # backward fill# null value is replaced by the after value [means null value gets after value]

/tmp/ipykernel_1047/759426405.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method="bfill") # backward fill# null value is replaced by the after value [means null value gets after value]

0    25.0
1    30.0
2    35.0
3    29.0
4    29.0
5    25.0
Name: Age, dtype: float64

In [ ]:
df["Name"].replace("srija","sri")

0    balasri
1      leela
2        sri
3      mouni
4    sravani
5    balasri
Name: Name, dtype: object

In [ ]:
# dealing with duplicate values
df_dup=df[df.duplicated()]
df_dup

      Name   Age Dept   Salary  promoted salary
5  balasri  25.0   HR  55000.0         550000.0

In [ ]:
df_dup=df[df.duplicated(keep="last")] # last duplicate value is not treated as duplicate value
df_dup

      Name   Age Dept   Salary  promoted salary
0  balasri  25.0   HR  55000.0         550000.0

In [ ]:
df_dup=df[df.duplicated(keep="first")]  # it is defult # first value not treated as duplicate value
df_dup

      Name   Age Dept   Salary  promoted salary
5  balasri  25.0   HR  55000.0         550000.0

In [ ]:
df=df.drop_duplicates() # remove duplicate value row
df

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0         750000.0
3    mouni   NaN       IT  67000.0         670000.0
4  sravani  29.0       HR      NaN              NaN

In [ ]:
df["promoted salary"]=df["promoted salary"].apply(lambda x:x/10 if x>650000 else x)
df

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0          75000.0
3    mouni   NaN       IT  67000.0          67000.0
4  sravani  29.0       HR      NaN              NaN

In [ ]:
# apply and lambda
def multiply_age(x):
  return x*2
df["Age"]=df["Age"].apply(multiply_age)
df

      Name   Age     Dept   Salary  promoted salary
0  balasri  50.0       HR  55000.0         550000.0
1    leela  60.0       IT  65000.0         650000.0
2    srija  70.0  Finance  75000.0          75000.0
3    mouni   NaN       IT  67000.0          67000.0
4  sravani  58.0       HR      NaN              NaN

In [ ]:
df["Age"]=df["Age"].apply(lambda x:x/2)
df

      Name   Age     Dept   Salary  promoted salary
0  balasri  25.0       HR  55000.0         550000.0
1    leela  30.0       IT  65000.0         650000.0
2    srija  35.0  Finance  75000.0          75000.0
3    mouni   NaN       IT  67000.0          67000.0
4  sravani  29.0       HR      NaN              NaN

In [ ]:
# joins and merges
department_info={
    "Dept":["HR","IT","Finance"],
    "location":["New york","san Francisco","chicago"],
    "Manager":["laura","steve","nina"]
}
df2=pd.DataFrame(department_info)
df2

      Dept       location Manager
0       HR       New york   laura
1       IT  san Francisco   steve
2  Finance        chicago    nina

In [ ]:
# concat
pd.concat([df,df2])

      Name   Age     Dept   Salary  promoted salary       location Manager
0  balasri  25.0       HR  55000.0         550000.0            NaN     NaN
1    leela  30.0       IT  65000.0         650000.0            NaN     NaN
2    srija  35.0  Finance  75000.0          75000.0            NaN     NaN
3    mouni   NaN       IT  67000.0          67000.0            NaN     NaN
4  sravani  29.0       HR      NaN              NaN            NaN     NaN
0      NaN   NaN       HR      NaN              NaN       New york   laura
1      NaN   NaN       IT      NaN              NaN  san Francisco   steve
2      NaN   NaN  Finance      NaN              NaN        chicago    nina

In [ ]:
pd.concat([df,df2],axis=1)

,Name,Age,Dept,Salary,promoted salary,Dept,location,Manager
0,balasri,25.0,HR,55000.0,550000.0,HR,New york,laura
1,leela,30.0,IT,65000.0,650000.0,IT,san Francisco,steve
2,srija,35.0,Finance,75000.0,75000.0,Finance,chicago,nina
3,mouni,NaN,IT,67000.0,67000.0,NaN,NaN,NaN
4,sravani,29.0,HR,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.merge(df,df2,on="Dept") # if the name is same in both dataframe then we simple use on or otherwise we use left_on="1st dataframe lo name",right_on=" 2nd dataframe lo name"

      Name   Age     Dept   Salary  promoted salary       location Manager
0  balasri  25.0       HR  55000.0         550000.0       New york   laura
1    leela  30.0       IT  65000.0         650000.0  san Francisco   steve
2    srija  35.0  Finance  75000.0          75000.0        chicago    nina
3    mouni   NaN       IT  67000.0          67000.0  san Francisco   steve
4  sravani  29.0       HR      NaN              NaN       New york   laura

In [229]:
# impoerting files
data=pd.read_csv("/iris.csv")
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [230]:
data.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [232]:
data.shape

(150, 5)

In [233]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB